// frontend/react/001-tic-tac-toe/src/components/Board.js
import React from "react";
import Square from "./Square";

export default function Board({ xNext, squares, onPlay }) {
    function handleClick(i) {
        if (squares[i] || calculateWinner(squares))
            return;

        const nextSquares = squares.slice();
        nextSquares[i] = xNext ? "X" : "O";
        onPlay(nextSquares);
    }

    const winner = calculateWinner(squares);
    let status;
    if (winner)
        status = "Winner: " + winner;
    else
        status = "Next player: " + (xNext ? "X" : "O");

    return (
        <div>
            <div className="status">{status}</div>
            <div className="board-row">
                <Square value={squares[0]} onSquareClick={() => handleClick(0)} />
                <Square value={squares[1]} onSquareClick={() => handleClick(1)} />
                <Square value={squares[2]} onSquareClick={() => handleClick(2)} />
            </div>
            <div className="board-row">
                <Square value={squares[3]} onSquareClick={() => handleClick(3)} />
                <Square value={squares[4]} onSquareClick={() => handleClick(4)} />
                <Square value={squares[5]} onSquareClick={() => handleClick(5)} />
            </div>
            <div className="board-row">
                <Square value={squares[6]} onSquareClick={() => handleClick(6)} />
                <Square value={squares[7]} onSquareClick={() => handleClick(7)} />
                <Square value={squares[8]} onSquareClick={() => handleClick(8)} />
            </div>
        </div>
    );
}

function calculateWinner(squares) {
    const lines = [
        [0, 1, 2],
        [3, 4, 5],
        [6, 7, 8],
        [0, 3, 6],
        [1, 4, 7],
        [2, 5, 8],
        [0, 4, 8],
        [2, 4, 6]
    ];
    for (let i = 0; i < lines.length; i++) {
        const [a, b, c] = lines[i];
        if (squares[a] && squares[a] === squares[b] && squares[a] === squares[c]) {
            return squares[a];
        }
    }
    return null;
}

// frontend/angular/002-tic-tac-toe/src/app/board/board.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-board',
  templateUrl: './board.component.html',
  styleUrls: ['./board.component.css']
})
export class BoardComponent {
  status: string = "Next player: X";
  squares: string[] = Array(9).fill(null);
  xNext: boolean = true;

  onNotify(square_id: number) {
    // if the square is already filled, do nothing
    if (this.squares[square_id] || calculateWinner(this.squares))
      return;

    // update the square with the current player
    this.squares[square_id] = (this.xNext ? "X" : "O");

    // Check if after the move, there is a winner. If so, update the status.
    const winner: string | null = calculateWinner(this.squares);
    if (winner) {
      this.status = "Winner: " + winner;
      return;
    }

    if (this.squares.every((square) => square != null)) {
      this.status = "Draw";
      return;
    }

    // Otherwise, update the status to show the next player
    this.xNext = !this.xNext;
    this.status = "Next player: " + (this.xNext ? "X" : "O");
  }
}


function calculateWinner(squares: any) {
  const lines = [
    [0, 1, 2],
    [3, 4, 5],
    [6, 7, 8],
    [0, 3, 6],
    [1, 4, 7],
    [2, 5, 8],
    [0, 4, 8],
    [2, 4, 6]
  ];
  for (let i = 0; i < lines.length; i++) {
    const [a, b, c] = lines[i];
    if (squares[a] && squares[a] === squares[b] && squares[a] === squares[c]) {
      return squares[a];
    }
  }
  return null;
}
<div>
    <div class="status">{{status}}</div>
    <div class="board-row">
        <!-- <Square value={squares[0]} onSquareClick={()=> handleClick(0)} /> -->
        <app-square [value]="squares[0]" (notify)="onNotify(0)"></app-square>
        <app-square [value]="squares[1]" (notify)="onNotify(1)"></app-square>
        <app-square [value]="squares[2]" (notify)="onNotify(2)"></app-square>
    </div>
    <div class="board-row">
        <app-square [value]="squares[3]" (notify)="onNotify(3)"></app-square>
        <app-square [value]="squares[4]" (notify)="onNotify(4)"></app-square>
        <app-square [value]="squares[5]" (notify)="onNotify(5)"></app-square>
    </div>
    <div class="board-row">
        <app-square [value]="squares[6]" (notify)="onNotify(6)"></app-square>
        <app-square [value]="squares[7]" (notify)="onNotify(7)"></app-square>
        <app-square [value]="squares[8]" (notify)="onNotify(8)"></app-square>
    </div>
    <div class="reset-link">
        <a title='Restart the game' href='/'>Reset</a>
    </div>
</div>
